name: .NET Core

defaults:
  run:
    working-directory: ./Source

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      binaryPath: DafnyLS/bin/Release/netcoreapp3.1
    outputs:
      binaries: ${{env.binaryPath}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack Binaries
      run: cd ${{env.binaryPath}} && zip -r DafnyLS.zip .
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: DafnyLS.zip
        path: ./Source/${{env.binaryPath}}/DafnyLS.zip
