name: .NET Core

defaults:
  run:
    working-directory: ./Source

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    name: ${{matrix.suffix}}
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            suffix: ubuntu-16.04
            z3: z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04
            chmod: true
            coverage: true
          - os: windows-2019
            suffix: win
            z3: z3-4.8.4.d6df51951f4c-x64-win
            chmod: false
            coverage: false
          - os: macos-10.15
            suffix: osx-10.14.1
            z3: z3-4.8.4.d6df51951f4c-x64-osx-10.14.1
            chmod: true
            coverage: false
    env:
      binaryPath: DafnyLS/bin/Release/netcoreapp3.1
      testPath: DafnyLS.IntegrationTest/bin/Debug/netcoreapp3.1
      z3BaseUri: https://github.com/Z3Prover/z3/releases/download/z3-4.8.4
      coverageFile: coverage.cobertura.xml
    outputs:
      binaries: ${{env.binaryPath}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Load Z3
      shell: pwsh
      run: |
        Invoke-WebRequest ${{env.z3BaseUri}}/${{matrix.z3}}.zip -OutFile z3.zip
        Expand-Archive z3.zip .
        Remove-Item z3.zip
        Copy-Item ${{matrix.z3}} ${{env.binaryPath}}/z3 -Recurse
        Copy-Item ${{matrix.z3}} ${{env.testPath}}/z3 -Recurse
    - name: Set Permissions
      if: ${{matrix.chmod}}
      run: chmod +x ${{env.testPath}}/z3/bin/z3
    - name: Run Tests
      if: ${{!matrix.coverage}}
      run: dotnet test --no-restore --verbosity normal
    - name: Run Test Coverage
      if: ${{matrix.coverage}}
      run: |
        dotnet test --no-restore --verbosity normal --settings DafnyLS.IntegrationTest/coverlet.runsettings
        mv DafnyLS.IntegrationTest/TestResults/*/${{env.coverageFile}} ./${{env.coverageFile}}
        ls -al .
    - name: Upload Coverage Report
      if: ${{matrix.coverage}}
      uses: codecov/codecov-action@v1
      with:
        file: ./Source/${{env.coverageFile}}
    - name: Upload Artifacts
      if: ${{github.ref == 'refs/heads/master'}}
      uses: actions/upload-artifact@v2
      with:
        name: DafnyLS-${{matrix.suffix}}
        path: ./Source/${{env.binaryPath}}/
